### ISSUE TITLE
Callback Proc error

### ISSUE THREAD

**Issue by osterwood** [kareemk/yapper#8]
I updated to the newest version of yapper (and YapDatabase) and when I try to write to a newly created database I get the following error:

```
callbacks.rb:65:in `run_callbacks:': expected Proc with 5 arguments (got 4) (ArgumentError)
    from persistence.rb:139:in `block in save:'
    from db.rb:298:in `block in run'
    from db.rb:304:in `run'
    from db.rb:40:in `execute'
    from persistence.rb:136:in `save:'
    from persistence.rb:20:in `block in create:'
    from persistence.rb:20:in `create:'
```

The model looks like this:

```
class Configuration

  include Yapper::Document
  include Yapper::Timestamps

  include YapperHelpers

  field :name,   :type => String
  field :album,  :type => String
  field :config

  index :name
  index :album
end
```

I am doing

Configuration.create(album: "server", name:  "single")

app_delegate.rb is setting db_version with

```
Yapper::Settings.db_version = 1
```

Any ideas?

**Comment by kareemk** [comment]
Trying pointing your Gemfile to the gitub repo:

`gem 'motion-yapper',    :github => 'kareemk/yapper'`

Otherwise I'll try and reproduce this later today.

**Comment by osterwood** [comment]
Thanks so much for the quick reply!

I am getting build errors around motion-support using your version (it seems to conflict with ProMotion and motion-require in strange ways).  I have created a fork of yapper that pulls in parts of motion-support, but doesn't use the whole gem here:  https://github.com/osterwood/yapper

I will trying to reproduce using your version.
